// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCFRNfZhxbMfHoGXPzkZ_CmdnwzauJO4xA',
    appId: '1:73201833829:web:7fd8de04995d6bdc84738c',
    messagingSenderId: '73201833829',
    projectId: 'realtime-quiz-app-1aed7',
    authDomain: 'realtime-quiz-app-1aed7.firebaseapp.com',
    databaseURL: 'https://realtime-quiz-app-1aed7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'realtime-quiz-app-1aed7.appspot.com',
    measurementId: 'G-7214X7Q52M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_lYK__zO73b8s8iyFToYkTAcDYBi9-ZA',
    appId: '1:73201833829:android:c42509c67520167284738c',
    messagingSenderId: '73201833829',
    projectId: 'realtime-quiz-app-1aed7',
    databaseURL: 'https://realtime-quiz-app-1aed7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'realtime-quiz-app-1aed7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZD-V7sKBuC8AXAxohRG3xNCjZtrmBlXU',
    appId: '1:73201833829:ios:31f646b6acf3e24484738c',
    messagingSenderId: '73201833829',
    projectId: 'realtime-quiz-app-1aed7',
    databaseURL: 'https://realtime-quiz-app-1aed7-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'realtime-quiz-app-1aed7.appspot.com',
    iosBundleId: 'com.example.realtimeQuizApp',
  );
}
